spring.application.name=cadense

spring.config.import=optional:file:.env[.properties]


# Core 
spring.profiles.active=h2

# Docker
spring.docker.compose.enabled=false

# base endpoint configs
api-endpoint = api/v1

# Cookie SameSite configuration:  "Lax", "None" or "Strict"   
cookie-same-site =${COOKIE_SAME_SITE:None}

# CORS
frontend-domain = ${FRONTEND_DOMAIN:https://localhost:5173}


# jwt secrets
jwt-secret=${JWT_SECRET:0kuSAcoQ7qpnLOO92S2VCrkc8g2tiDrWgZ5V+lzYWqA=}
access-token-duration-minutes=${ACCESS_TOKEN_DURATION_MINUTES:5}
refresh-token-duration-days=${REFRESH_TOKEN_DURATION_DAYS:30}

# SSL config (ones for localhost were created by mkcert)
server.ssl.key-store=${SSL_KEYSTORE_PATH: file:.certs/localhost+1.p12 }
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:changeit}
server.ssl.key-store-type=PKCS12
server.port=8443

# Stripe testing
stripe.api.key=${STRIPE_API_KEY:}
stripe.success.url=${STRIPE_SUCCESS_URL:https://localhost:5173/success}
stripe.cancel.url=${STRIPE_CANCEL_URL:https://localhost:5173/cancel}

